namespace Attendance_management_system
{
    partial class frmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmMain));
            this.panel2 = new System.Windows.Forms.Panel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btnresults = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btninvoice = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLogout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnfaculty = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnadmission = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnattendance = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnstudent = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btndashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.DashboardPanel = new System.Windows.Forms.Panel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.label2 = new System.Windows.Forms.Label();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(1)))), ((int)(((byte)(123)))), ((int)(((byte)(255)))));
            this.panel2.Controls.Add(this.label2);
            this.panel2.Controls.Add(this.bunifuPictureBox1);
            this.panel2.Controls.Add(this.pictureBox2);
            this.panel2.Controls.Add(this.label1);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(1441, 34);
            this.panel2.TabIndex = 1;
            this.panel2.Paint += new System.Windows.Forms.PaintEventHandler(this.panel2_Paint);
            // 
            // pictureBox2
            // 
            this.pictureBox2.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox2.Image = global::Attendance_management_system.Properties.Resources.x_regular_24;
            this.pictureBox2.Location = new System.Drawing.Point(1389, 2);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(36, 29);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 1;
            this.pictureBox2.TabStop = false;
            this.pictureBox2.Click += new System.EventHandler(this.pictureBox2_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(72, 3);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(500, 23);
            this.label1.TabIndex = 3;
            this.label1.Text = "MKP IT Services | Attendance Managment System | Sujit Project";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(183)))), ((int)(((byte)(184)))), ((int)(((byte)(186)))));
            this.panel1.Controls.Add(this.btnresults);
            this.panel1.Controls.Add(this.btninvoice);
            this.panel1.Controls.Add(this.btnLogout);
            this.panel1.Controls.Add(this.btnfaculty);
            this.panel1.Controls.Add(this.btnadmission);
            this.panel1.Controls.Add(this.btnattendance);
            this.panel1.Controls.Add(this.btnstudent);
            this.panel1.Controls.Add(this.btndashboard);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 34);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(215, 713);
            this.panel1.TabIndex = 2;
            // 
            // btnresults
            // 
            this.btnresults.AllowAnimations = true;
            this.btnresults.AllowMouseEffects = true;
            this.btnresults.AllowToggling = false;
            this.btnresults.AnimationSpeed = 10;
            this.btnresults.AutoGenerateColors = false;
            this.btnresults.AutoRoundBorders = false;
            this.btnresults.AutoSizeLeftIcon = false;
            this.btnresults.AutoSizeRightIcon = true;
            this.btnresults.BackColor = System.Drawing.Color.Transparent;
            this.btnresults.BackColor1 = System.Drawing.Color.Transparent;
            this.btnresults.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnresults.BackgroundImage")));
            this.btnresults.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnresults.ButtonText = "Results";
            this.btnresults.ButtonTextMarginLeft = 0;
            this.btnresults.ColorContrastOnClick = 45;
            this.btnresults.ColorContrastOnHover = 45;
            this.btnresults.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnresults.CustomizableEdges = borderEdges9;
            this.btnresults.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnresults.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnresults.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnresults.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnresults.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnresults.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnresults.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnresults.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnresults.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnresults.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnresults.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.btnresults.IconMarginLeft = 11;
            this.btnresults.IconPadding = 10;
            this.btnresults.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnresults.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnresults.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnresults.IconSize = 25;
            this.btnresults.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnresults.IdleBorderRadius = 1;
            this.btnresults.IdleBorderThickness = 1;
            this.btnresults.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnresults.IdleIconLeftImage = global::Attendance_management_system.Properties.Resources.statisctics;
            this.btnresults.IdleIconRightImage = null;
            this.btnresults.IndicateFocus = false;
            this.btnresults.Location = new System.Drawing.Point(0, 390);
            this.btnresults.Name = "btnresults";
            this.btnresults.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnresults.OnDisabledState.BorderRadius = 1;
            this.btnresults.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnresults.OnDisabledState.BorderThickness = 1;
            this.btnresults.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnresults.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnresults.OnDisabledState.IconLeftImage = null;
            this.btnresults.OnDisabledState.IconRightImage = null;
            this.btnresults.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnresults.onHoverState.BorderRadius = 1;
            this.btnresults.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnresults.onHoverState.BorderThickness = 1;
            this.btnresults.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnresults.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnresults.onHoverState.IconLeftImage = null;
            this.btnresults.onHoverState.IconRightImage = null;
            this.btnresults.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnresults.OnIdleState.BorderRadius = 1;
            this.btnresults.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnresults.OnIdleState.BorderThickness = 1;
            this.btnresults.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnresults.OnIdleState.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnresults.OnIdleState.IconLeftImage = global::Attendance_management_system.Properties.Resources.statisctics;
            this.btnresults.OnIdleState.IconRightImage = null;
            this.btnresults.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnresults.OnPressedState.BorderRadius = 1;
            this.btnresults.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnresults.OnPressedState.BorderThickness = 1;
            this.btnresults.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnresults.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnresults.OnPressedState.IconLeftImage = null;
            this.btnresults.OnPressedState.IconRightImage = null;
            this.btnresults.Size = new System.Drawing.Size(215, 65);
            this.btnresults.TabIndex = 4;
            this.btnresults.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnresults.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnresults.TextMarginLeft = 0;
            this.btnresults.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnresults.UseDefaultRadiusAndThickness = true;
            this.btnresults.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // btninvoice
            // 
            this.btninvoice.AllowAnimations = true;
            this.btninvoice.AllowMouseEffects = true;
            this.btninvoice.AllowToggling = false;
            this.btninvoice.AnimationSpeed = 10;
            this.btninvoice.AutoGenerateColors = false;
            this.btninvoice.AutoRoundBorders = false;
            this.btninvoice.AutoSizeLeftIcon = false;
            this.btninvoice.AutoSizeRightIcon = true;
            this.btninvoice.BackColor = System.Drawing.Color.Transparent;
            this.btninvoice.BackColor1 = System.Drawing.Color.Transparent;
            this.btninvoice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btninvoice.BackgroundImage")));
            this.btninvoice.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btninvoice.ButtonText = "Invoice";
            this.btninvoice.ButtonTextMarginLeft = 0;
            this.btninvoice.ColorContrastOnClick = 45;
            this.btninvoice.ColorContrastOnHover = 45;
            this.btninvoice.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btninvoice.CustomizableEdges = borderEdges10;
            this.btninvoice.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btninvoice.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btninvoice.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btninvoice.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btninvoice.Dock = System.Windows.Forms.DockStyle.Top;
            this.btninvoice.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btninvoice.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btninvoice.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btninvoice.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btninvoice.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btninvoice.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.btninvoice.IconMarginLeft = 11;
            this.btninvoice.IconPadding = 10;
            this.btninvoice.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btninvoice.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btninvoice.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btninvoice.IconSize = 25;
            this.btninvoice.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btninvoice.IdleBorderRadius = 1;
            this.btninvoice.IdleBorderThickness = 1;
            this.btninvoice.IdleFillColor = System.Drawing.Color.Transparent;
            this.btninvoice.IdleIconLeftImage = global::Attendance_management_system.Properties.Resources.invoice;
            this.btninvoice.IdleIconRightImage = null;
            this.btninvoice.IndicateFocus = false;
            this.btninvoice.Location = new System.Drawing.Point(0, 325);
            this.btninvoice.Name = "btninvoice";
            this.btninvoice.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btninvoice.OnDisabledState.BorderRadius = 1;
            this.btninvoice.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btninvoice.OnDisabledState.BorderThickness = 1;
            this.btninvoice.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btninvoice.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btninvoice.OnDisabledState.IconLeftImage = null;
            this.btninvoice.OnDisabledState.IconRightImage = null;
            this.btninvoice.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btninvoice.onHoverState.BorderRadius = 1;
            this.btninvoice.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btninvoice.onHoverState.BorderThickness = 1;
            this.btninvoice.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btninvoice.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btninvoice.onHoverState.IconLeftImage = null;
            this.btninvoice.onHoverState.IconRightImage = null;
            this.btninvoice.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btninvoice.OnIdleState.BorderRadius = 1;
            this.btninvoice.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btninvoice.OnIdleState.BorderThickness = 1;
            this.btninvoice.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btninvoice.OnIdleState.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btninvoice.OnIdleState.IconLeftImage = global::Attendance_management_system.Properties.Resources.invoice;
            this.btninvoice.OnIdleState.IconRightImage = null;
            this.btninvoice.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btninvoice.OnPressedState.BorderRadius = 1;
            this.btninvoice.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btninvoice.OnPressedState.BorderThickness = 1;
            this.btninvoice.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btninvoice.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btninvoice.OnPressedState.IconLeftImage = null;
            this.btninvoice.OnPressedState.IconRightImage = null;
            this.btninvoice.Size = new System.Drawing.Size(215, 65);
            this.btninvoice.TabIndex = 4;
            this.btninvoice.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btninvoice.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btninvoice.TextMarginLeft = 0;
            this.btninvoice.TextPadding = new System.Windows.Forms.Padding(0);
            this.btninvoice.UseDefaultRadiusAndThickness = true;
            // 
            // btnLogout
            // 
            this.btnLogout.AllowAnimations = true;
            this.btnLogout.AllowMouseEffects = true;
            this.btnLogout.AllowToggling = false;
            this.btnLogout.AnimationSpeed = 10;
            this.btnLogout.AutoGenerateColors = false;
            this.btnLogout.AutoRoundBorders = false;
            this.btnLogout.AutoSizeLeftIcon = false;
            this.btnLogout.AutoSizeRightIcon = true;
            this.btnLogout.BackColor = System.Drawing.Color.Transparent;
            this.btnLogout.BackColor1 = System.Drawing.Color.Transparent;
            this.btnLogout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogout.BackgroundImage")));
            this.btnLogout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.ButtonText = "Log out";
            this.btnLogout.ButtonTextMarginLeft = 0;
            this.btnLogout.ColorContrastOnClick = 45;
            this.btnLogout.ColorContrastOnHover = 45;
            this.btnLogout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnLogout.CustomizableEdges = borderEdges11;
            this.btnLogout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLogout.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLogout.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnLogout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogout.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.btnLogout.IconMarginLeft = 11;
            this.btnLogout.IconPadding = 10;
            this.btnLogout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLogout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLogout.IconSize = 25;
            this.btnLogout.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnLogout.IdleBorderRadius = 1;
            this.btnLogout.IdleBorderThickness = 1;
            this.btnLogout.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnLogout.IdleIconLeftImage = global::Attendance_management_system.Properties.Resources.power_off;
            this.btnLogout.IdleIconRightImage = null;
            this.btnLogout.IndicateFocus = false;
            this.btnLogout.Location = new System.Drawing.Point(0, 619);
            this.btnLogout.Name = "btnLogout";
            this.btnLogout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogout.OnDisabledState.BorderRadius = 1;
            this.btnLogout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.OnDisabledState.BorderThickness = 1;
            this.btnLogout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogout.OnDisabledState.IconLeftImage = null;
            this.btnLogout.OnDisabledState.IconRightImage = null;
            this.btnLogout.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLogout.onHoverState.BorderRadius = 1;
            this.btnLogout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.onHoverState.BorderThickness = 1;
            this.btnLogout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLogout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLogout.onHoverState.IconLeftImage = null;
            this.btnLogout.onHoverState.IconRightImage = null;
            this.btnLogout.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnLogout.OnIdleState.BorderRadius = 1;
            this.btnLogout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.OnIdleState.BorderThickness = 1;
            this.btnLogout.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnLogout.OnIdleState.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnLogout.OnIdleState.IconLeftImage = global::Attendance_management_system.Properties.Resources.power_off;
            this.btnLogout.OnIdleState.IconRightImage = null;
            this.btnLogout.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLogout.OnPressedState.BorderRadius = 1;
            this.btnLogout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogout.OnPressedState.BorderThickness = 1;
            this.btnLogout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLogout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLogout.OnPressedState.IconLeftImage = null;
            this.btnLogout.OnPressedState.IconRightImage = null;
            this.btnLogout.Size = new System.Drawing.Size(215, 72);
            this.btnLogout.TabIndex = 3;
            this.btnLogout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLogout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogout.TextMarginLeft = 0;
            this.btnLogout.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btnLogout.UseDefaultRadiusAndThickness = true;
            this.btnLogout.Click += new System.EventHandler(this.bunifuButton4_Click);
            // 
            // btnfaculty
            // 
            this.btnfaculty.AllowAnimations = true;
            this.btnfaculty.AllowMouseEffects = true;
            this.btnfaculty.AllowToggling = false;
            this.btnfaculty.AnimationSpeed = 10;
            this.btnfaculty.AutoGenerateColors = false;
            this.btnfaculty.AutoRoundBorders = false;
            this.btnfaculty.AutoSizeLeftIcon = false;
            this.btnfaculty.AutoSizeRightIcon = true;
            this.btnfaculty.BackColor = System.Drawing.Color.Transparent;
            this.btnfaculty.BackColor1 = System.Drawing.Color.Transparent;
            this.btnfaculty.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnfaculty.BackgroundImage")));
            this.btnfaculty.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnfaculty.ButtonText = "Faculty";
            this.btnfaculty.ButtonTextMarginLeft = 0;
            this.btnfaculty.ColorContrastOnClick = 45;
            this.btnfaculty.ColorContrastOnHover = 45;
            this.btnfaculty.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnfaculty.CustomizableEdges = borderEdges12;
            this.btnfaculty.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnfaculty.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnfaculty.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnfaculty.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnfaculty.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnfaculty.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnfaculty.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnfaculty.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnfaculty.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnfaculty.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnfaculty.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.btnfaculty.IconMarginLeft = 11;
            this.btnfaculty.IconPadding = 10;
            this.btnfaculty.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnfaculty.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnfaculty.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnfaculty.IconSize = 25;
            this.btnfaculty.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnfaculty.IdleBorderRadius = 1;
            this.btnfaculty.IdleBorderThickness = 1;
            this.btnfaculty.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnfaculty.IdleIconLeftImage = global::Attendance_management_system.Properties.Resources.people;
            this.btnfaculty.IdleIconRightImage = null;
            this.btnfaculty.IndicateFocus = false;
            this.btnfaculty.Location = new System.Drawing.Point(0, 260);
            this.btnfaculty.Name = "btnfaculty";
            this.btnfaculty.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnfaculty.OnDisabledState.BorderRadius = 1;
            this.btnfaculty.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnfaculty.OnDisabledState.BorderThickness = 1;
            this.btnfaculty.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnfaculty.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnfaculty.OnDisabledState.IconLeftImage = null;
            this.btnfaculty.OnDisabledState.IconRightImage = null;
            this.btnfaculty.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnfaculty.onHoverState.BorderRadius = 1;
            this.btnfaculty.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnfaculty.onHoverState.BorderThickness = 1;
            this.btnfaculty.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnfaculty.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnfaculty.onHoverState.IconLeftImage = null;
            this.btnfaculty.onHoverState.IconRightImage = null;
            this.btnfaculty.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnfaculty.OnIdleState.BorderRadius = 1;
            this.btnfaculty.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnfaculty.OnIdleState.BorderThickness = 1;
            this.btnfaculty.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnfaculty.OnIdleState.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnfaculty.OnIdleState.IconLeftImage = global::Attendance_management_system.Properties.Resources.people;
            this.btnfaculty.OnIdleState.IconRightImage = null;
            this.btnfaculty.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnfaculty.OnPressedState.BorderRadius = 1;
            this.btnfaculty.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnfaculty.OnPressedState.BorderThickness = 1;
            this.btnfaculty.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnfaculty.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnfaculty.OnPressedState.IconLeftImage = null;
            this.btnfaculty.OnPressedState.IconRightImage = null;
            this.btnfaculty.Size = new System.Drawing.Size(215, 65);
            this.btnfaculty.TabIndex = 3;
            this.btnfaculty.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnfaculty.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnfaculty.TextMarginLeft = 0;
            this.btnfaculty.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnfaculty.UseDefaultRadiusAndThickness = true;
            this.btnfaculty.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // btnadmission
            // 
            this.btnadmission.AllowAnimations = true;
            this.btnadmission.AllowMouseEffects = true;
            this.btnadmission.AllowToggling = false;
            this.btnadmission.AnimationSpeed = 10;
            this.btnadmission.AutoGenerateColors = false;
            this.btnadmission.AutoRoundBorders = false;
            this.btnadmission.AutoSizeLeftIcon = false;
            this.btnadmission.AutoSizeRightIcon = true;
            this.btnadmission.BackColor = System.Drawing.Color.Transparent;
            this.btnadmission.BackColor1 = System.Drawing.Color.Transparent;
            this.btnadmission.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnadmission.BackgroundImage")));
            this.btnadmission.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnadmission.ButtonText = "Admission";
            this.btnadmission.ButtonTextMarginLeft = 0;
            this.btnadmission.ColorContrastOnClick = 45;
            this.btnadmission.ColorContrastOnHover = 45;
            this.btnadmission.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btnadmission.CustomizableEdges = borderEdges13;
            this.btnadmission.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnadmission.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnadmission.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnadmission.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnadmission.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnadmission.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnadmission.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnadmission.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnadmission.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnadmission.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnadmission.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.btnadmission.IconMarginLeft = 11;
            this.btnadmission.IconPadding = 10;
            this.btnadmission.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnadmission.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnadmission.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnadmission.IconSize = 25;
            this.btnadmission.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnadmission.IdleBorderRadius = 1;
            this.btnadmission.IdleBorderThickness = 1;
            this.btnadmission.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnadmission.IdleIconLeftImage = global::Attendance_management_system.Properties.Resources.list_ul_regular_24;
            this.btnadmission.IdleIconRightImage = null;
            this.btnadmission.IndicateFocus = false;
            this.btnadmission.Location = new System.Drawing.Point(0, 195);
            this.btnadmission.Name = "btnadmission";
            this.btnadmission.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnadmission.OnDisabledState.BorderRadius = 1;
            this.btnadmission.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnadmission.OnDisabledState.BorderThickness = 1;
            this.btnadmission.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnadmission.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnadmission.OnDisabledState.IconLeftImage = null;
            this.btnadmission.OnDisabledState.IconRightImage = null;
            this.btnadmission.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnadmission.onHoverState.BorderRadius = 1;
            this.btnadmission.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnadmission.onHoverState.BorderThickness = 1;
            this.btnadmission.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnadmission.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnadmission.onHoverState.IconLeftImage = null;
            this.btnadmission.onHoverState.IconRightImage = null;
            this.btnadmission.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnadmission.OnIdleState.BorderRadius = 1;
            this.btnadmission.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnadmission.OnIdleState.BorderThickness = 1;
            this.btnadmission.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnadmission.OnIdleState.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnadmission.OnIdleState.IconLeftImage = global::Attendance_management_system.Properties.Resources.list_ul_regular_24;
            this.btnadmission.OnIdleState.IconRightImage = null;
            this.btnadmission.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnadmission.OnPressedState.BorderRadius = 1;
            this.btnadmission.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnadmission.OnPressedState.BorderThickness = 1;
            this.btnadmission.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnadmission.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnadmission.OnPressedState.IconLeftImage = null;
            this.btnadmission.OnPressedState.IconRightImage = null;
            this.btnadmission.Size = new System.Drawing.Size(215, 65);
            this.btnadmission.TabIndex = 3;
            this.btnadmission.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnadmission.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnadmission.TextMarginLeft = 0;
            this.btnadmission.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnadmission.UseDefaultRadiusAndThickness = true;
            this.btnadmission.Click += new System.EventHandler(this.btnadmission_Click_1);
            // 
            // btnattendance
            // 
            this.btnattendance.AllowAnimations = true;
            this.btnattendance.AllowMouseEffects = true;
            this.btnattendance.AllowToggling = false;
            this.btnattendance.AnimationSpeed = 10;
            this.btnattendance.AutoGenerateColors = false;
            this.btnattendance.AutoRoundBorders = false;
            this.btnattendance.AutoSizeLeftIcon = false;
            this.btnattendance.AutoSizeRightIcon = true;
            this.btnattendance.BackColor = System.Drawing.Color.Transparent;
            this.btnattendance.BackColor1 = System.Drawing.Color.Transparent;
            this.btnattendance.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnattendance.BackgroundImage")));
            this.btnattendance.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnattendance.ButtonText = "Attendance";
            this.btnattendance.ButtonTextMarginLeft = 0;
            this.btnattendance.ColorContrastOnClick = 45;
            this.btnattendance.ColorContrastOnHover = 45;
            this.btnattendance.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btnattendance.CustomizableEdges = borderEdges14;
            this.btnattendance.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnattendance.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnattendance.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnattendance.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnattendance.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnattendance.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnattendance.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnattendance.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnattendance.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnattendance.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnattendance.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.btnattendance.IconMarginLeft = 11;
            this.btnattendance.IconPadding = 10;
            this.btnattendance.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnattendance.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnattendance.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnattendance.IconSize = 25;
            this.btnattendance.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnattendance.IdleBorderRadius = 1;
            this.btnattendance.IdleBorderThickness = 1;
            this.btnattendance.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnattendance.IdleIconLeftImage = global::Attendance_management_system.Properties.Resources.book_bookmark_solid_24;
            this.btnattendance.IdleIconRightImage = null;
            this.btnattendance.IndicateFocus = false;
            this.btnattendance.Location = new System.Drawing.Point(0, 130);
            this.btnattendance.Name = "btnattendance";
            this.btnattendance.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnattendance.OnDisabledState.BorderRadius = 1;
            this.btnattendance.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnattendance.OnDisabledState.BorderThickness = 1;
            this.btnattendance.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnattendance.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnattendance.OnDisabledState.IconLeftImage = null;
            this.btnattendance.OnDisabledState.IconRightImage = null;
            this.btnattendance.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnattendance.onHoverState.BorderRadius = 1;
            this.btnattendance.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnattendance.onHoverState.BorderThickness = 1;
            this.btnattendance.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnattendance.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnattendance.onHoverState.IconLeftImage = null;
            this.btnattendance.onHoverState.IconRightImage = null;
            this.btnattendance.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnattendance.OnIdleState.BorderRadius = 1;
            this.btnattendance.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnattendance.OnIdleState.BorderThickness = 1;
            this.btnattendance.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnattendance.OnIdleState.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnattendance.OnIdleState.IconLeftImage = global::Attendance_management_system.Properties.Resources.book_bookmark_solid_24;
            this.btnattendance.OnIdleState.IconRightImage = null;
            this.btnattendance.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnattendance.OnPressedState.BorderRadius = 1;
            this.btnattendance.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnattendance.OnPressedState.BorderThickness = 1;
            this.btnattendance.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnattendance.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnattendance.OnPressedState.IconLeftImage = null;
            this.btnattendance.OnPressedState.IconRightImage = null;
            this.btnattendance.Size = new System.Drawing.Size(215, 65);
            this.btnattendance.TabIndex = 3;
            this.btnattendance.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnattendance.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnattendance.TextMarginLeft = 0;
            this.btnattendance.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnattendance.UseDefaultRadiusAndThickness = true;
            this.btnattendance.Click += new System.EventHandler(this.btnattendance_Click);
            // 
            // btnstudent
            // 
            this.btnstudent.AllowAnimations = true;
            this.btnstudent.AllowMouseEffects = true;
            this.btnstudent.AllowToggling = false;
            this.btnstudent.AnimationSpeed = 10;
            this.btnstudent.AutoGenerateColors = false;
            this.btnstudent.AutoRoundBorders = false;
            this.btnstudent.AutoSizeLeftIcon = false;
            this.btnstudent.AutoSizeRightIcon = true;
            this.btnstudent.BackColor = System.Drawing.Color.Transparent;
            this.btnstudent.BackColor1 = System.Drawing.Color.Transparent;
            this.btnstudent.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnstudent.BackgroundImage")));
            this.btnstudent.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnstudent.ButtonText = "Students";
            this.btnstudent.ButtonTextMarginLeft = 0;
            this.btnstudent.ColorContrastOnClick = 45;
            this.btnstudent.ColorContrastOnHover = 45;
            this.btnstudent.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.btnstudent.CustomizableEdges = borderEdges15;
            this.btnstudent.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnstudent.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnstudent.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnstudent.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnstudent.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnstudent.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnstudent.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnstudent.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnstudent.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnstudent.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnstudent.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.btnstudent.IconMarginLeft = 11;
            this.btnstudent.IconPadding = 10;
            this.btnstudent.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnstudent.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnstudent.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnstudent.IconSize = 25;
            this.btnstudent.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnstudent.IdleBorderRadius = 1;
            this.btnstudent.IdleBorderThickness = 1;
            this.btnstudent.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnstudent.IdleIconLeftImage = global::Attendance_management_system.Properties.Resources.group;
            this.btnstudent.IdleIconRightImage = null;
            this.btnstudent.IndicateFocus = false;
            this.btnstudent.Location = new System.Drawing.Point(0, 65);
            this.btnstudent.Name = "btnstudent";
            this.btnstudent.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnstudent.OnDisabledState.BorderRadius = 1;
            this.btnstudent.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnstudent.OnDisabledState.BorderThickness = 1;
            this.btnstudent.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnstudent.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnstudent.OnDisabledState.IconLeftImage = null;
            this.btnstudent.OnDisabledState.IconRightImage = null;
            this.btnstudent.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnstudent.onHoverState.BorderRadius = 1;
            this.btnstudent.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnstudent.onHoverState.BorderThickness = 1;
            this.btnstudent.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnstudent.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnstudent.onHoverState.IconLeftImage = null;
            this.btnstudent.onHoverState.IconRightImage = null;
            this.btnstudent.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnstudent.OnIdleState.BorderRadius = 1;
            this.btnstudent.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnstudent.OnIdleState.BorderThickness = 1;
            this.btnstudent.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnstudent.OnIdleState.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btnstudent.OnIdleState.IconLeftImage = global::Attendance_management_system.Properties.Resources.group;
            this.btnstudent.OnIdleState.IconRightImage = null;
            this.btnstudent.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnstudent.OnPressedState.BorderRadius = 1;
            this.btnstudent.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnstudent.OnPressedState.BorderThickness = 1;
            this.btnstudent.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnstudent.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnstudent.OnPressedState.IconLeftImage = null;
            this.btnstudent.OnPressedState.IconRightImage = null;
            this.btnstudent.Size = new System.Drawing.Size(215, 65);
            this.btnstudent.TabIndex = 3;
            this.btnstudent.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnstudent.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnstudent.TextMarginLeft = 0;
            this.btnstudent.TextPadding = new System.Windows.Forms.Padding(3, 0, 0, 0);
            this.btnstudent.UseDefaultRadiusAndThickness = true;
            this.btnstudent.Click += new System.EventHandler(this.btnstudent_Click);
            // 
            // btndashboard
            // 
            this.btndashboard.AllowAnimations = true;
            this.btndashboard.AllowMouseEffects = true;
            this.btndashboard.AllowToggling = false;
            this.btndashboard.AnimationSpeed = 10;
            this.btndashboard.AutoGenerateColors = false;
            this.btndashboard.AutoRoundBorders = false;
            this.btndashboard.AutoSizeLeftIcon = false;
            this.btndashboard.AutoSizeRightIcon = true;
            this.btndashboard.BackColor = System.Drawing.Color.Transparent;
            this.btndashboard.BackColor1 = System.Drawing.Color.Transparent;
            this.btndashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btndashboard.BackgroundImage")));
            this.btndashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btndashboard.ButtonText = "Dashboard";
            this.btndashboard.ButtonTextMarginLeft = 0;
            this.btndashboard.ColorContrastOnClick = 45;
            this.btndashboard.ColorContrastOnHover = 45;
            this.btndashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges16.BottomLeft = true;
            borderEdges16.BottomRight = true;
            borderEdges16.TopLeft = true;
            borderEdges16.TopRight = true;
            this.btndashboard.CustomizableEdges = borderEdges16;
            this.btndashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btndashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btndashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btndashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btndashboard.Dock = System.Windows.Forms.DockStyle.Top;
            this.btndashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btndashboard.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btndashboard.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btndashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btndashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btndashboard.IconLeftPadding = new System.Windows.Forms.Padding(15, 3, 3, 3);
            this.btndashboard.IconMarginLeft = 11;
            this.btndashboard.IconPadding = 10;
            this.btndashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btndashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btndashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btndashboard.IconSize = 25;
            this.btndashboard.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btndashboard.IdleBorderRadius = 1;
            this.btndashboard.IdleBorderThickness = 1;
            this.btndashboard.IdleFillColor = System.Drawing.Color.Transparent;
            this.btndashboard.IdleIconLeftImage = global::Attendance_management_system.Properties.Resources.dashboard_solid_24;
            this.btndashboard.IdleIconRightImage = null;
            this.btndashboard.IndicateFocus = false;
            this.btndashboard.Location = new System.Drawing.Point(0, 0);
            this.btndashboard.Name = "btndashboard";
            this.btndashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btndashboard.OnDisabledState.BorderRadius = 1;
            this.btndashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btndashboard.OnDisabledState.BorderThickness = 1;
            this.btndashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btndashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btndashboard.OnDisabledState.IconLeftImage = null;
            this.btndashboard.OnDisabledState.IconRightImage = null;
            this.btndashboard.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btndashboard.onHoverState.BorderRadius = 1;
            this.btndashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btndashboard.onHoverState.BorderThickness = 1;
            this.btndashboard.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btndashboard.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btndashboard.onHoverState.IconLeftImage = null;
            this.btndashboard.onHoverState.IconRightImage = null;
            this.btndashboard.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btndashboard.OnIdleState.BorderRadius = 1;
            this.btndashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btndashboard.OnIdleState.BorderThickness = 1;
            this.btndashboard.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btndashboard.OnIdleState.ForeColor = System.Drawing.SystemColors.InactiveCaptionText;
            this.btndashboard.OnIdleState.IconLeftImage = global::Attendance_management_system.Properties.Resources.dashboard_solid_24;
            this.btndashboard.OnIdleState.IconRightImage = null;
            this.btndashboard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btndashboard.OnPressedState.BorderRadius = 1;
            this.btndashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btndashboard.OnPressedState.BorderThickness = 1;
            this.btndashboard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btndashboard.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btndashboard.OnPressedState.IconLeftImage = null;
            this.btndashboard.OnPressedState.IconRightImage = null;
            this.btndashboard.Size = new System.Drawing.Size(215, 65);
            this.btndashboard.TabIndex = 3;
            this.btndashboard.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btndashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btndashboard.TextMarginLeft = 0;
            this.btndashboard.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btndashboard.UseDefaultRadiusAndThickness = true;
            this.btndashboard.Click += new System.EventHandler(this.btndashboard_Click);
            // 
            // DashboardPanel
            // 
            this.DashboardPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.DashboardPanel.Location = new System.Drawing.Point(215, 34);
            this.DashboardPanel.Name = "DashboardPanel";
            this.DashboardPanel.Size = new System.Drawing.Size(1226, 713);
            this.DashboardPanel.TabIndex = 4;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 14;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(15, 3);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(29, 29);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.bunifuPictureBox1.Click += new System.EventHandler(this.bunifuPictureBox1_Click);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(1255, 3);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(120, 23);
            this.label2.TabIndex = 4;
            this.label2.Text = "Administrative";
            this.label2.Click += new System.EventHandler(this.label2_Click);
            // 
            // frmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Gainsboro;
            this.ClientSize = new System.Drawing.Size(1441, 747);
            this.Controls.Add(this.DashboardPanel);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.panel2);
            this.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ForeColor = System.Drawing.SystemColors.ControlText;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.MaximumSize = new System.Drawing.Size(1441, 747);
            this.MinimumSize = new System.Drawing.Size(1441, 747);
            this.Name = "frmMain";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Attendance Managment System";
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnstudent;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btndashboard;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLogout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnfaculty;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnadmission;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnattendance;
        private System.Windows.Forms.Panel DashboardPanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btninvoice;
        private System.Windows.Forms.PictureBox pictureBox2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnresults;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.Label label2;
    }
}